// Generated by scripts/generate-lexicons.mjs from lexicons/**/*.json.
// Do not edit by hand.

export const NS = {
  "artifact": "app.graycard.artifact",
  "catalog": {
    "cameraType": "app.graycard.catalog.cameraType",
    "chemistryType": "app.graycard.catalog.chemistryType",
    "devRecipe": "app.graycard.catalog.devRecipe",
    "enlargerType": "app.graycard.catalog.enlargerType",
    "enlargingLensType": "app.graycard.catalog.enlargingLensType",
    "filmStock": "app.graycard.catalog.filmStock",
    "filterType": "app.graycard.catalog.filterType",
    "lab": "app.graycard.catalog.lab",
    "lensType": "app.graycard.catalog.lensType",
    "lightSourceType": "app.graycard.catalog.lightSourceType",
    "meterType": "app.graycard.catalog.meterType",
    "paperType": "app.graycard.catalog.paperType",
    "printerType": "app.graycard.catalog.printerType",
    "scannerType": "app.graycard.catalog.scannerType",
    "scanProfile": "app.graycard.catalog.scanProfile"
  },
  "edit": {
    "recipe": "app.graycard.edit.recipe"
  },
  "gallery": {
    "defaults": "app.graycard.gallery.defaults"
  },
  "instance": {
    "camera": "app.graycard.instance.camera",
    "chemistry": "app.graycard.instance.chemistry",
    "enlarger": "app.graycard.instance.enlarger",
    "enlargingLens": "app.graycard.instance.enlargingLens",
    "exposure": "app.graycard.instance.exposure",
    "filmRoll": "app.graycard.instance.filmRoll",
    "filmStockpile": "app.graycard.instance.filmStockpile",
    "filter": "app.graycard.instance.filter",
    "intermediate": "app.graycard.instance.intermediate",
    "labAccount": "app.graycard.instance.labAccount",
    "lens": "app.graycard.instance.lens",
    "lightSource": "app.graycard.instance.lightSource",
    "meter": "app.graycard.instance.meter",
    "printer": "app.graycard.instance.printer",
    "scanner": "app.graycard.instance.scanner",
    "storageLocation": "app.graycard.instance.storageLocation"
  },
  "meter": {
    "calibration": "app.graycard.meter.calibration",
    "reading": "app.graycard.meter.reading"
  },
  "photo": {
    "capture": "app.graycard.photo.capture",
    "workflow": "app.graycard.photo.workflow"
  },
  "process": {
    "developSession": "app.graycard.process.developSession",
    "digitizeSession": "app.graycard.process.digitizeSession",
    "editSession": "app.graycard.process.editSession",
    "maintenanceSession": "app.graycard.process.maintenanceSession",
    "printSession": "app.graycard.process.printSession",
    "renderSession": "app.graycard.process.renderSession"
  },
  "rule": {
    "batch": "app.graycard.rule.batch"
  },
  "scene": {
    "edge": "app.graycard.scene.edge",
    "graph": "app.graycard.scene.graph",
    "node": "app.graycard.scene.node",
    "ontology": "app.graycard.scene.ontology",
    "region": "app.graycard.scene.region"
  },
  "session": {
    "capture": "app.graycard.session.capture"
  },
  "setup": "app.graycard.setup",
  "workflow": {
    "run": "app.graycard.workflow.run",
    "stage": "app.graycard.workflow.stage",
    "template": "app.graycard.workflow.template"
  }
} as const;
export const RECORD_NSID_LIST = [
  "app.graycard.artifact",
  "app.graycard.catalog.cameraType",
  "app.graycard.catalog.chemistryType",
  "app.graycard.catalog.devRecipe",
  "app.graycard.catalog.enlargerType",
  "app.graycard.catalog.enlargingLensType",
  "app.graycard.catalog.filmStock",
  "app.graycard.catalog.filterType",
  "app.graycard.catalog.lab",
  "app.graycard.catalog.lensType",
  "app.graycard.catalog.lightSourceType",
  "app.graycard.catalog.meterType",
  "app.graycard.catalog.paperType",
  "app.graycard.catalog.printerType",
  "app.graycard.catalog.scannerType",
  "app.graycard.catalog.scanProfile",
  "app.graycard.edit.recipe",
  "app.graycard.gallery.defaults",
  "app.graycard.instance.camera",
  "app.graycard.instance.chemistry",
  "app.graycard.instance.enlarger",
  "app.graycard.instance.enlargingLens",
  "app.graycard.instance.exposure",
  "app.graycard.instance.filmRoll",
  "app.graycard.instance.filmStockpile",
  "app.graycard.instance.filter",
  "app.graycard.instance.intermediate",
  "app.graycard.instance.labAccount",
  "app.graycard.instance.lens",
  "app.graycard.instance.lightSource",
  "app.graycard.instance.meter",
  "app.graycard.instance.printer",
  "app.graycard.instance.scanner",
  "app.graycard.instance.storageLocation",
  "app.graycard.meter.calibration",
  "app.graycard.meter.reading",
  "app.graycard.photo.capture",
  "app.graycard.photo.workflow",
  "app.graycard.process.developSession",
  "app.graycard.process.digitizeSession",
  "app.graycard.process.editSession",
  "app.graycard.process.maintenanceSession",
  "app.graycard.process.printSession",
  "app.graycard.process.renderSession",
  "app.graycard.rule.batch",
  "app.graycard.scene.edge",
  "app.graycard.scene.graph",
  "app.graycard.scene.node",
  "app.graycard.scene.ontology",
  "app.graycard.scene.region",
  "app.graycard.session.capture",
  "app.graycard.setup",
  "app.graycard.workflow.run",
  "app.graycard.workflow.stage",
  "app.graycard.workflow.template"
] as const;
export const CATALOG_KINDS = Object.freeze(["cameraType","chemistryType","enlargerType","enlargingLensType","filmStock","filterType","lab","lensType","lightSourceType","meterType","paperType","printerType","scannerType","scanProfile"]);
export const ALL_CATALOG_KINDS = Object.freeze(Object.keys(NS.catalog));
export const INSTANCE_KINDS = Object.freeze(Object.keys(NS.instance));
